//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Commands.Definitions;
    
    
    public partial class TelemetryOutputEnableCommand {
        
        public static string CreateIPAddress() {
            // 
            // Creates a new instance of the System.String class IPAddress.
            // 
            string IPAddress = String.Empty;
            IPAddress = "192.168.001.200";
            return IPAddress;
        }
    }
}
