//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Commands.Definitions;
    
    
    public partial class TelemetryOutputEnableCommand {
        
        public static GES.Communications.CCSDSCommand CreateCommand() {
            // 
            // Creates a new instance of the GES.Communications.CCSDSCommand class Command.
            // 
            GES.Communications.CCSDSCommand Command = new GES.Communications.CCSDSCommand();
            Command.Name = "TelemetryOutputEnable";
            return Command;
        }
    }
}
