//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Commands.Definitions;
    
    
    public partial class TelemetryOutputEnableCommand {
        
        public static GES.Commands.Definitions.CFSCommandDefinition CreateCFSCommandDefinition() {
            // 
            // Creates a new instance of the GES.Commands.Definitions.CFSCommandDefinition class CFSCommandDefinition.
            // 
            GES.Commands.Definitions.CFSCommandDefinition CFSCommandDefinition = new GES.Commands.Definitions.CFSCommandDefinition();
            CFSCommandDefinition.CommandSecondaryHeader.FunctionCode = 5;
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "IPAddress";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "";
            dataattributes1.MinValue = "";
            dataattributes1.MaxValue = "";
            dataattributes1.DataType = "String";
            dataattributes1.BitLength = 128;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "IPAddress";
            CFSCommandDefinition.ApplicationDataAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1))};
            CFSCommandDefinition.PrimaryHeader.Version = 0;
            CFSCommandDefinition.PrimaryHeader.Type = 1;
            CFSCommandDefinition.PrimaryHeader.SecondaryFlag = 1;
            CFSCommandDefinition.PrimaryHeader.ApplicationId = 7968;
            CFSCommandDefinition.PrimaryHeader.Grouping = 3;
            CFSCommandDefinition.PrimaryHeader.SequenceCount = 0;
            CFSCommandDefinition.PrimaryHeader.PacketDataLength = 17;
            CFSCommandDefinition.XORChecksum.StopIndex = 24;
            return CFSCommandDefinition;
        }
    }
}
