//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    public partial class EventServicesHousekeepingTelemetreyData {
        
        public static CFS.DataStructures.EventServicesApplicationTelemetryData CreateApp8Data() {
            // 
            // Creates a new instance of the CFS.DataStructures.EventServicesApplicationTelemetryData class App8Data.
            // 
            CFS.DataStructures.EventServicesApplicationTelemetryData App8Data = new CFS.DataStructures.EventServicesApplicationTelemetryData();
            return App8Data;
        }
    }
}
