//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    using CFS.DataStructures;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class EventServicesHousekeepingTelemetreyData : MTI.Core.Component {
        
        private byte _CommandCounter;
        
        private byte _CommandErrorCounter;
        
        private byte _MessageFormatMode;
        
        private byte _MessageTrunCounter;
        
        private byte _UnregisteredAppCounter;
        
        private byte _OutputPort;
        
        private byte _LogFullFlag;
        
        private byte _LogMode;
        
        private ushort _MessageSendCounter;
        
        private ushort _LogOverflowCounter;
        
        private byte _LogEnabled;
        
        private byte _Spare1;
        
        private byte _Spare2;
        
        private byte _Spare3;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App1Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App2Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App3Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App4Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App5Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App6Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App7Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App8Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App9Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App10Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App11Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App12Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App13Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App14Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App15Data;
        
        private CFS.DataStructures.EventServicesApplicationTelemetryData _App16Data;
        
        public EventServicesHousekeepingTelemetreyData() {
            // 
            // Construct _CommandCounter
            // 
            this._CommandCounter = EventServicesHousekeepingTelemetreyData.CreateCommandCounter();
            // 
            // Construct _CommandErrorCounter
            // 
            this._CommandErrorCounter = EventServicesHousekeepingTelemetreyData.CreateCommandErrorCounter();
            // 
            // Construct _MessageFormatMode
            // 
            this._MessageFormatMode = EventServicesHousekeepingTelemetreyData.CreateMessageFormatMode();
            // 
            // Construct _MessageTrunCounter
            // 
            this._MessageTrunCounter = EventServicesHousekeepingTelemetreyData.CreateMessageTrunCounter();
            // 
            // Construct _UnregisteredAppCounter
            // 
            this._UnregisteredAppCounter = EventServicesHousekeepingTelemetreyData.CreateUnregisteredAppCounter();
            // 
            // Construct _OutputPort
            // 
            this._OutputPort = EventServicesHousekeepingTelemetreyData.CreateOutputPort();
            // 
            // Construct _LogFullFlag
            // 
            this._LogFullFlag = EventServicesHousekeepingTelemetreyData.CreateLogFullFlag();
            // 
            // Construct _LogMode
            // 
            this._LogMode = EventServicesHousekeepingTelemetreyData.CreateLogMode();
            // 
            // Construct _MessageSendCounter
            // 
            this._MessageSendCounter = EventServicesHousekeepingTelemetreyData.CreateMessageSendCounter();
            // 
            // Construct _LogOverflowCounter
            // 
            this._LogOverflowCounter = EventServicesHousekeepingTelemetreyData.CreateLogOverflowCounter();
            // 
            // Construct _LogEnabled
            // 
            this._LogEnabled = EventServicesHousekeepingTelemetreyData.CreateLogEnabled();
            // 
            // Construct _Spare1
            // 
            this._Spare1 = EventServicesHousekeepingTelemetreyData.CreateSpare1();
            // 
            // Construct _Spare2
            // 
            this._Spare2 = EventServicesHousekeepingTelemetreyData.CreateSpare2();
            // 
            // Construct _Spare3
            // 
            this._Spare3 = EventServicesHousekeepingTelemetreyData.CreateSpare3();
            // 
            // Construct _App1Data
            // 
            this._App1Data = EventServicesHousekeepingTelemetreyData.CreateApp1Data();
            // 
            // Construct _App2Data
            // 
            this._App2Data = EventServicesHousekeepingTelemetreyData.CreateApp2Data();
            // 
            // Construct _App3Data
            // 
            this._App3Data = EventServicesHousekeepingTelemetreyData.CreateApp3Data();
            // 
            // Construct _App4Data
            // 
            this._App4Data = EventServicesHousekeepingTelemetreyData.CreateApp4Data();
            // 
            // Construct _App5Data
            // 
            this._App5Data = EventServicesHousekeepingTelemetreyData.CreateApp5Data();
            // 
            // Construct _App6Data
            // 
            this._App6Data = EventServicesHousekeepingTelemetreyData.CreateApp6Data();
            // 
            // Construct _App7Data
            // 
            this._App7Data = EventServicesHousekeepingTelemetreyData.CreateApp7Data();
            // 
            // Construct _App8Data
            // 
            this._App8Data = EventServicesHousekeepingTelemetreyData.CreateApp8Data();
            // 
            // Construct _App9Data
            // 
            this._App9Data = EventServicesHousekeepingTelemetreyData.CreateApp9Data();
            // 
            // Construct _App10Data
            // 
            this._App10Data = EventServicesHousekeepingTelemetreyData.CreateApp10Data();
            // 
            // Construct _App11Data
            // 
            this._App11Data = EventServicesHousekeepingTelemetreyData.CreateApp11Data();
            // 
            // Construct _App12Data
            // 
            this._App12Data = EventServicesHousekeepingTelemetreyData.CreateApp12Data();
            // 
            // Construct _App13Data
            // 
            this._App13Data = EventServicesHousekeepingTelemetreyData.CreateApp13Data();
            // 
            // Construct _App14Data
            // 
            this._App14Data = EventServicesHousekeepingTelemetreyData.CreateApp14Data();
            // 
            // Construct _App15Data
            // 
            this._App15Data = EventServicesHousekeepingTelemetreyData.CreateApp15Data();
            // 
            // Construct _App16Data
            // 
            this._App16Data = EventServicesHousekeepingTelemetreyData.CreateApp16Data();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual byte CommandCounter {
            get {
                return this._CommandCounter;
            }
            set {
                this._CommandCounter = value;
                this.OnPropertyChanged("CommandCounter");
            }
        }
        
        public virtual byte CommandErrorCounter {
            get {
                return this._CommandErrorCounter;
            }
            set {
                this._CommandErrorCounter = value;
                this.OnPropertyChanged("CommandErrorCounter");
            }
        }
        
        public virtual byte MessageFormatMode {
            get {
                return this._MessageFormatMode;
            }
            set {
                this._MessageFormatMode = value;
                this.OnPropertyChanged("MessageFormatMode");
            }
        }
        
        public virtual byte MessageTrunCounter {
            get {
                return this._MessageTrunCounter;
            }
            set {
                this._MessageTrunCounter = value;
                this.OnPropertyChanged("MessageTrunCounter");
            }
        }
        
        public virtual byte UnregisteredAppCounter {
            get {
                return this._UnregisteredAppCounter;
            }
            set {
                this._UnregisteredAppCounter = value;
                this.OnPropertyChanged("UnregisteredAppCounter");
            }
        }
        
        public virtual byte OutputPort {
            get {
                return this._OutputPort;
            }
            set {
                this._OutputPort = value;
                this.OnPropertyChanged("OutputPort");
            }
        }
        
        public virtual byte LogFullFlag {
            get {
                return this._LogFullFlag;
            }
            set {
                this._LogFullFlag = value;
                this.OnPropertyChanged("LogFullFlag");
            }
        }
        
        public virtual byte LogMode {
            get {
                return this._LogMode;
            }
            set {
                this._LogMode = value;
                this.OnPropertyChanged("LogMode");
            }
        }
        
        public virtual ushort MessageSendCounter {
            get {
                return this._MessageSendCounter;
            }
            set {
                this._MessageSendCounter = value;
                this.OnPropertyChanged("MessageSendCounter");
            }
        }
        
        public virtual ushort LogOverflowCounter {
            get {
                return this._LogOverflowCounter;
            }
            set {
                this._LogOverflowCounter = value;
                this.OnPropertyChanged("LogOverflowCounter");
            }
        }
        
        public virtual byte LogEnabled {
            get {
                return this._LogEnabled;
            }
            set {
                this._LogEnabled = value;
                this.OnPropertyChanged("LogEnabled");
            }
        }
        
        public virtual byte Spare1 {
            get {
                return this._Spare1;
            }
            set {
                this._Spare1 = value;
                this.OnPropertyChanged("Spare1");
            }
        }
        
        public virtual byte Spare2 {
            get {
                return this._Spare2;
            }
            set {
                this._Spare2 = value;
                this.OnPropertyChanged("Spare2");
            }
        }
        
        public virtual byte Spare3 {
            get {
                return this._Spare3;
            }
            set {
                this._Spare3 = value;
                this.OnPropertyChanged("Spare3");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App1Data {
            get {
                return this._App1Data;
            }
            set {
                this._App1Data = value;
                this.OnPropertyChanged("App1Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App2Data {
            get {
                return this._App2Data;
            }
            set {
                this._App2Data = value;
                this.OnPropertyChanged("App2Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App3Data {
            get {
                return this._App3Data;
            }
            set {
                this._App3Data = value;
                this.OnPropertyChanged("App3Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App4Data {
            get {
                return this._App4Data;
            }
            set {
                this._App4Data = value;
                this.OnPropertyChanged("App4Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App5Data {
            get {
                return this._App5Data;
            }
            set {
                this._App5Data = value;
                this.OnPropertyChanged("App5Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App6Data {
            get {
                return this._App6Data;
            }
            set {
                this._App6Data = value;
                this.OnPropertyChanged("App6Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App7Data {
            get {
                return this._App7Data;
            }
            set {
                this._App7Data = value;
                this.OnPropertyChanged("App7Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App8Data {
            get {
                return this._App8Data;
            }
            set {
                this._App8Data = value;
                this.OnPropertyChanged("App8Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App9Data {
            get {
                return this._App9Data;
            }
            set {
                this._App9Data = value;
                this.OnPropertyChanged("App9Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App10Data {
            get {
                return this._App10Data;
            }
            set {
                this._App10Data = value;
                this.OnPropertyChanged("App10Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App11Data {
            get {
                return this._App11Data;
            }
            set {
                this._App11Data = value;
                this.OnPropertyChanged("App11Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App12Data {
            get {
                return this._App12Data;
            }
            set {
                this._App12Data = value;
                this.OnPropertyChanged("App12Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App13Data {
            get {
                return this._App13Data;
            }
            set {
                this._App13Data = value;
                this.OnPropertyChanged("App13Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App14Data {
            get {
                return this._App14Data;
            }
            set {
                this._App14Data = value;
                this.OnPropertyChanged("App14Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App15Data {
            get {
                return this._App15Data;
            }
            set {
                this._App15Data = value;
                this.OnPropertyChanged("App15Data");
            }
        }
        
        public virtual CFS.DataStructures.EventServicesApplicationTelemetryData App16Data {
            get {
                return this._App16Data;
            }
            set {
                this._App16Data = value;
                this.OnPropertyChanged("App16Data");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
