//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class CFSCommand {
        
        public static CFS.DataStructures.CommandSecondaryHeader CreateCommandSecondaryHeader() {
            // 
            // Creates a new instance of the CFS.DataStructures.CommandSecondaryHeader class CommandSecondaryHeader.
            // 
            CFS.DataStructures.CommandSecondaryHeader CommandSecondaryHeader = new CFS.DataStructures.CommandSecondaryHeader();
            return CommandSecondaryHeader;
        }
    }
}
