//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class CommandSecondaryHeader : MTI.Core.Component {
        
        private byte _FunctionCode;
        
        private byte _Checksum;
        
        public CommandSecondaryHeader() {
            // 
            // Construct _FunctionCode
            // 
            this._FunctionCode = CommandSecondaryHeader.CreateFunctionCode();
            // 
            // Construct _Checksum
            // 
            this._Checksum = CommandSecondaryHeader.CreateChecksum();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual byte FunctionCode {
            get {
                return this._FunctionCode;
            }
            set {
                this._FunctionCode = value;
                this.OnPropertyChanged("FunctionCode");
            }
        }
        
        public virtual byte Checksum {
            get {
                return this._Checksum;
            }
            set {
                this._Checksum = value;
                this.OnPropertyChanged("Checksum");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
