//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Telemetry {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Telemetry.Definitions;
    using CFS.DataStructures;
    
    
    public partial class ExecutiveServicesHousekeepingTelemetery {
        
        public static CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData CreateESHousekeepingTelemetryData() {
            // 
            // Creates a new instance of the CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData class ESHousekeepingTelemetryData.
            // 
            CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData ESHousekeepingTelemetryData = new CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData();
            return ESHousekeepingTelemetryData;
        }
    }
}
