//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Telemetry {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Telemetry.Definitions;
    using CFS.DataStructures;
    
    
    public partial class ExecutiveServicesHousekeepingTelemetery {
        
        public static GES.Communications.CCSDSTelemetry CreateCCSDSTelemetry() {
            // 
            // Creates a new instance of the GES.Communications.CCSDSTelemetry class CCSDSTelemetry.
            // 
            GES.Communications.CCSDSTelemetry CCSDSTelemetry = new GES.Communications.CCSDSTelemetry();
            CCSDSTelemetry.Name = "ExecutiveServicesHousekeepingTelemetry";
            return CCSDSTelemetry;
        }
    }
}
