//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Telemetry {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Telemetry.Definitions;
    using CFS.DataStructures;
    
    
    public partial class ExecutiveServicesHousekeepingTelemetery {
        
        public static GES.Telemetry.Definitions.CFSTelemetryDefinition CreateCFSTelemetryDefinition() {
            // 
            // Creates a new instance of the GES.Telemetry.Definitions.CFSTelemetryDefinition class CFSTelemetryDefinition.
            // 
            GES.Telemetry.Definitions.CFSTelemetryDefinition CFSTelemetryDefinition = new GES.Telemetry.Definitions.CFSTelemetryDefinition();
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "CommandCounter";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "0";
            dataattributes1.MinValue = "0";
            dataattributes1.MaxValue = "255";
            dataattributes1.DataType = "Byte";
            dataattributes1.BitLength = 8;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "ESHousekeepingTelemetryData.CommandCounter";
            GES.Communications.DataAttributes dataattributes2 = new GES.Communications.DataAttributes();
            dataattributes2.Name = "CommandErrorCounter";
            dataattributes2.Static = false;
            dataattributes2.DefaultValue = "0";
            dataattributes2.MinValue = "0";
            dataattributes2.MaxValue = "255";
            dataattributes2.DataType = "Byte";
            dataattributes2.BitLength = 8;
            dataattributes2.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes2.Equation = "";
            dataattributes2.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes2.LocalPathName = "ESHousekeepingTelemetryData.CommandErrorCounter";
            GES.Communications.DataAttributes dataattributes3 = new GES.Communications.DataAttributes();
            dataattributes3.Name = "CFECoreChecksum";
            dataattributes3.Static = false;
            dataattributes3.DefaultValue = "0";
            dataattributes3.MinValue = "0";
            dataattributes3.MaxValue = "65535";
            dataattributes3.DataType = "UInt16";
            dataattributes3.BitLength = 16;
            dataattributes3.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes3.Equation = "";
            dataattributes3.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes3.LocalPathName = "ESHousekeepingTelemetryData.CFECoreChecksum";
            GES.Communications.DataAttributes dataattributes4 = new GES.Communications.DataAttributes();
            dataattributes4.Name = "CFEMajorVersion";
            dataattributes4.Static = false;
            dataattributes4.DefaultValue = "0";
            dataattributes4.MinValue = "0";
            dataattributes4.MaxValue = "255";
            dataattributes4.DataType = "Byte";
            dataattributes4.BitLength = 8;
            dataattributes4.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes4.Equation = "";
            dataattributes4.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes4.LocalPathName = "ESHousekeepingTelemetryData.CFEMajorVersion";
            GES.Communications.DataAttributes dataattributes5 = new GES.Communications.DataAttributes();
            dataattributes5.Name = "CFEMinorVersion";
            dataattributes5.Static = false;
            dataattributes5.DefaultValue = "0";
            dataattributes5.MinValue = "0";
            dataattributes5.MaxValue = "255";
            dataattributes5.DataType = "Byte";
            dataattributes5.BitLength = 8;
            dataattributes5.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes5.Equation = "";
            dataattributes5.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes5.LocalPathName = "ESHousekeepingTelemetryData.CFEMinorVersion";
            GES.Communications.DataAttributes dataattributes6 = new GES.Communications.DataAttributes();
            dataattributes6.Name = "CFERevision";
            dataattributes6.Static = false;
            dataattributes6.DefaultValue = "0";
            dataattributes6.MinValue = "0";
            dataattributes6.MaxValue = "255";
            dataattributes6.DataType = "Byte";
            dataattributes6.BitLength = 8;
            dataattributes6.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes6.Equation = "";
            dataattributes6.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes6.LocalPathName = "ESHousekeepingTelemetryData.CFERevision";
            GES.Communications.DataAttributes dataattributes7 = new GES.Communications.DataAttributes();
            dataattributes7.Name = "CFEMissionRevision";
            dataattributes7.Static = false;
            dataattributes7.DefaultValue = "0";
            dataattributes7.MinValue = "0";
            dataattributes7.MaxValue = "255";
            dataattributes7.DataType = "Byte";
            dataattributes7.BitLength = 8;
            dataattributes7.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes7.Equation = "";
            dataattributes7.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes7.LocalPathName = "ESHousekeepingTelemetryData.CFEMissionRevision";
            GES.Communications.DataAttributes dataattributes8 = new GES.Communications.DataAttributes();
            dataattributes8.Name = "OSALMajorVersion";
            dataattributes8.Static = false;
            dataattributes8.DefaultValue = "0";
            dataattributes8.MinValue = "0";
            dataattributes8.MaxValue = "255";
            dataattributes8.DataType = "Byte";
            dataattributes8.BitLength = 8;
            dataattributes8.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes8.Equation = "";
            dataattributes8.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes8.LocalPathName = "ESHousekeepingTelemetryData.OSALMajorVersion";
            GES.Communications.DataAttributes dataattributes9 = new GES.Communications.DataAttributes();
            dataattributes9.Name = "OSALMinorVersion";
            dataattributes9.Static = false;
            dataattributes9.DefaultValue = "0";
            dataattributes9.MinValue = "0";
            dataattributes9.MaxValue = "255";
            dataattributes9.DataType = "Byte";
            dataattributes9.BitLength = 8;
            dataattributes9.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes9.Equation = "";
            dataattributes9.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes9.LocalPathName = "ESHousekeepingTelemetryData.OSALMinorVersion";
            GES.Communications.DataAttributes dataattributes10 = new GES.Communications.DataAttributes();
            dataattributes10.Name = "OSALRevision";
            dataattributes10.Static = false;
            dataattributes10.DefaultValue = "0";
            dataattributes10.MinValue = "0";
            dataattributes10.MaxValue = "255";
            dataattributes10.DataType = "Byte";
            dataattributes10.BitLength = 8;
            dataattributes10.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes10.Equation = "";
            dataattributes10.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes10.LocalPathName = "ESHousekeepingTelemetryData.OSALRevision";
            GES.Communications.DataAttributes dataattributes11 = new GES.Communications.DataAttributes();
            dataattributes11.Name = "OSALMissionRevision";
            dataattributes11.Static = false;
            dataattributes11.DefaultValue = "0";
            dataattributes11.MinValue = "0";
            dataattributes11.MaxValue = "255";
            dataattributes11.DataType = "Byte";
            dataattributes11.BitLength = 8;
            dataattributes11.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes11.Equation = "";
            dataattributes11.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes11.LocalPathName = "ESHousekeepingTelemetryData.OSALMissionRevision";
            GES.Communications.DataAttributes dataattributes12 = new GES.Communications.DataAttributes();
            dataattributes12.Name = "SysLogBytesUsed";
            dataattributes12.Static = false;
            dataattributes12.DefaultValue = "0";
            dataattributes12.MinValue = "0";
            dataattributes12.MaxValue = "4294967295";
            dataattributes12.DataType = "UInt32";
            dataattributes12.BitLength = 32;
            dataattributes12.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes12.Equation = "";
            dataattributes12.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes12.LocalPathName = "ESHousekeepingTelemetryData.SysLogBytesUsed";
            GES.Communications.DataAttributes dataattributes13 = new GES.Communications.DataAttributes();
            dataattributes13.Name = "SysLogSize";
            dataattributes13.Static = false;
            dataattributes13.DefaultValue = "0";
            dataattributes13.MinValue = "0";
            dataattributes13.MaxValue = "4294967295";
            dataattributes13.DataType = "UInt32";
            dataattributes13.BitLength = 32;
            dataattributes13.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes13.Equation = "";
            dataattributes13.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes13.LocalPathName = "ESHousekeepingTelemetryData.SysLogSize";
            GES.Communications.DataAttributes dataattributes14 = new GES.Communications.DataAttributes();
            dataattributes14.Name = "SysLogEntries";
            dataattributes14.Static = false;
            dataattributes14.DefaultValue = "0";
            dataattributes14.MinValue = "0";
            dataattributes14.MaxValue = "4294967295";
            dataattributes14.DataType = "UInt32";
            dataattributes14.BitLength = 32;
            dataattributes14.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes14.Equation = "";
            dataattributes14.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes14.LocalPathName = "ESHousekeepingTelemetryData.SysLogEntries";
            GES.Communications.DataAttributes dataattributes15 = new GES.Communications.DataAttributes();
            dataattributes15.Name = "SysLogMode";
            dataattributes15.Static = false;
            dataattributes15.DefaultValue = "0";
            dataattributes15.MinValue = "0";
            dataattributes15.MaxValue = "4294967295";
            dataattributes15.DataType = "UInt32";
            dataattributes15.BitLength = 32;
            dataattributes15.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes15.Equation = "";
            dataattributes15.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes15.LocalPathName = "ESHousekeepingTelemetryData.SysLogMode";
            GES.Communications.DataAttributes dataattributes16 = new GES.Communications.DataAttributes();
            dataattributes16.Name = "ERLogIndex";
            dataattributes16.Static = false;
            dataattributes16.DefaultValue = "0";
            dataattributes16.MinValue = "0";
            dataattributes16.MaxValue = "4294967295";
            dataattributes16.DataType = "UInt32";
            dataattributes16.BitLength = 32;
            dataattributes16.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes16.Equation = "";
            dataattributes16.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes16.LocalPathName = "ESHousekeepingTelemetryData.ERLogIndex";
            GES.Communications.DataAttributes dataattributes17 = new GES.Communications.DataAttributes();
            dataattributes17.Name = "ERLogEntries";
            dataattributes17.Static = false;
            dataattributes17.DefaultValue = "0";
            dataattributes17.MinValue = "0";
            dataattributes17.MaxValue = "4294967295";
            dataattributes17.DataType = "UInt32";
            dataattributes17.BitLength = 32;
            dataattributes17.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes17.Equation = "";
            dataattributes17.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes17.LocalPathName = "ESHousekeepingTelemetryData.ERLogEntries";
            GES.Communications.DataAttributes dataattributes18 = new GES.Communications.DataAttributes();
            dataattributes18.Name = "RegisteredCoreApps";
            dataattributes18.Static = false;
            dataattributes18.DefaultValue = "0";
            dataattributes18.MinValue = "0";
            dataattributes18.MaxValue = "4294967295";
            dataattributes18.DataType = "UInt32";
            dataattributes18.BitLength = 32;
            dataattributes18.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes18.Equation = "";
            dataattributes18.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes18.LocalPathName = "ESHousekeepingTelemetryData.RegisteredCoreApps";
            GES.Communications.DataAttributes dataattributes19 = new GES.Communications.DataAttributes();
            dataattributes19.Name = "RegisteredExternalApps";
            dataattributes19.Static = false;
            dataattributes19.DefaultValue = "0";
            dataattributes19.MinValue = "0";
            dataattributes19.MaxValue = "4294967295";
            dataattributes19.DataType = "UInt32";
            dataattributes19.BitLength = 32;
            dataattributes19.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes19.Equation = "";
            dataattributes19.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes19.LocalPathName = "ESHousekeepingTelemetryData.RegisteredExternalApps";
            GES.Communications.DataAttributes dataattributes20 = new GES.Communications.DataAttributes();
            dataattributes20.Name = "RegisteredTasks";
            dataattributes20.Static = false;
            dataattributes20.DefaultValue = "0";
            dataattributes20.MinValue = "0";
            dataattributes20.MaxValue = "4294967295";
            dataattributes20.DataType = "UInt32";
            dataattributes20.BitLength = 32;
            dataattributes20.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes20.Equation = "";
            dataattributes20.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes20.LocalPathName = "ESHousekeepingTelemetryData.RegisteredTasks";
            GES.Communications.DataAttributes dataattributes21 = new GES.Communications.DataAttributes();
            dataattributes21.Name = "RegisteredLibs";
            dataattributes21.Static = false;
            dataattributes21.DefaultValue = "0";
            dataattributes21.MinValue = "0";
            dataattributes21.MaxValue = "4294967295";
            dataattributes21.DataType = "UInt32";
            dataattributes21.BitLength = 32;
            dataattributes21.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes21.Equation = "";
            dataattributes21.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes21.LocalPathName = "ESHousekeepingTelemetryData.RegisteredLibs";
            GES.Communications.DataAttributes dataattributes22 = new GES.Communications.DataAttributes();
            dataattributes22.Name = "ResetType";
            dataattributes22.Static = false;
            dataattributes22.DefaultValue = "0";
            dataattributes22.MinValue = "0";
            dataattributes22.MaxValue = "4294967295";
            dataattributes22.DataType = "UInt32";
            dataattributes22.BitLength = 32;
            dataattributes22.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes22.Equation = "";
            dataattributes22.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes22.LocalPathName = "ESHousekeepingTelemetryData.ResetType";
            GES.Communications.DataAttributes dataattributes23 = new GES.Communications.DataAttributes();
            dataattributes23.Name = "ResetSubType";
            dataattributes23.Static = false;
            dataattributes23.DefaultValue = "0";
            dataattributes23.MinValue = "0";
            dataattributes23.MaxValue = "4294967295";
            dataattributes23.DataType = "UInt32";
            dataattributes23.BitLength = 32;
            dataattributes23.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes23.Equation = "";
            dataattributes23.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes23.LocalPathName = "ESHousekeepingTelemetryData.ResetSubType";
            GES.Communications.DataAttributes dataattributes24 = new GES.Communications.DataAttributes();
            dataattributes24.Name = "ProcessorResets";
            dataattributes24.Static = false;
            dataattributes24.DefaultValue = "0";
            dataattributes24.MinValue = "0";
            dataattributes24.MaxValue = "4294967295";
            dataattributes24.DataType = "UInt32";
            dataattributes24.BitLength = 32;
            dataattributes24.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes24.Equation = "";
            dataattributes24.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes24.LocalPathName = "ESHousekeepingTelemetryData.ProcessorResets";
            GES.Communications.DataAttributes dataattributes25 = new GES.Communications.DataAttributes();
            dataattributes25.Name = "MaxProcessorResets";
            dataattributes25.Static = false;
            dataattributes25.DefaultValue = "0";
            dataattributes25.MinValue = "0";
            dataattributes25.MaxValue = "4294967295";
            dataattributes25.DataType = "UInt32";
            dataattributes25.BitLength = 32;
            dataattributes25.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes25.Equation = "";
            dataattributes25.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes25.LocalPathName = "ESHousekeepingTelemetryData.MaxProcessorResets";
            GES.Communications.DataAttributes dataattributes26 = new GES.Communications.DataAttributes();
            dataattributes26.Name = "BootSource";
            dataattributes26.Static = false;
            dataattributes26.DefaultValue = "0";
            dataattributes26.MinValue = "0";
            dataattributes26.MaxValue = "4294967295";
            dataattributes26.DataType = "UInt32";
            dataattributes26.BitLength = 32;
            dataattributes26.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes26.Equation = "";
            dataattributes26.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes26.LocalPathName = "ESHousekeepingTelemetryData.BootSource";
            GES.Communications.DataAttributes dataattributes27 = new GES.Communications.DataAttributes();
            dataattributes27.Name = "PerfState";
            dataattributes27.Static = false;
            dataattributes27.DefaultValue = "0";
            dataattributes27.MinValue = "0";
            dataattributes27.MaxValue = "4294967295";
            dataattributes27.DataType = "UInt32";
            dataattributes27.BitLength = 32;
            dataattributes27.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes27.Equation = "";
            dataattributes27.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes27.LocalPathName = "ESHousekeepingTelemetryData.PerfState";
            GES.Communications.DataAttributes dataattributes28 = new GES.Communications.DataAttributes();
            dataattributes28.Name = "PerfMode";
            dataattributes28.Static = false;
            dataattributes28.DefaultValue = "0";
            dataattributes28.MinValue = "0";
            dataattributes28.MaxValue = "4294967295";
            dataattributes28.DataType = "UInt32";
            dataattributes28.BitLength = 32;
            dataattributes28.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes28.Equation = "";
            dataattributes28.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes28.LocalPathName = "ESHousekeepingTelemetryData.PerfMode";
            GES.Communications.DataAttributes dataattributes29 = new GES.Communications.DataAttributes();
            dataattributes29.Name = "PerfTriggerCount";
            dataattributes29.Static = false;
            dataattributes29.DefaultValue = "0";
            dataattributes29.MinValue = "0";
            dataattributes29.MaxValue = "4294967295";
            dataattributes29.DataType = "UInt32";
            dataattributes29.BitLength = 32;
            dataattributes29.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes29.Equation = "";
            dataattributes29.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes29.LocalPathName = "ESHousekeepingTelemetryData.PerfTriggerCount";
            GES.Communications.DataAttributes dataattributes30 = new GES.Communications.DataAttributes();
            dataattributes30.Name = "PerfFilterMask1";
            dataattributes30.Static = false;
            dataattributes30.DefaultValue = "0";
            dataattributes30.MinValue = "0";
            dataattributes30.MaxValue = "4294967295";
            dataattributes30.DataType = "UInt32";
            dataattributes30.BitLength = 32;
            dataattributes30.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes30.Equation = "";
            dataattributes30.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes30.LocalPathName = "ESHousekeepingTelemetryData.PerfFilterMask1";
            GES.Communications.DataAttributes dataattributes31 = new GES.Communications.DataAttributes();
            dataattributes31.Name = "PerfFilterMask2";
            dataattributes31.Static = false;
            dataattributes31.DefaultValue = "0";
            dataattributes31.MinValue = "0";
            dataattributes31.MaxValue = "4294967295";
            dataattributes31.DataType = "UInt32";
            dataattributes31.BitLength = 32;
            dataattributes31.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes31.Equation = "";
            dataattributes31.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes31.LocalPathName = "ESHousekeepingTelemetryData.PerfFilterMask2";
            GES.Communications.DataAttributes dataattributes32 = new GES.Communications.DataAttributes();
            dataattributes32.Name = "PerfFilterMask3";
            dataattributes32.Static = false;
            dataattributes32.DefaultValue = "0";
            dataattributes32.MinValue = "0";
            dataattributes32.MaxValue = "4294967295";
            dataattributes32.DataType = "UInt32";
            dataattributes32.BitLength = 32;
            dataattributes32.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes32.Equation = "";
            dataattributes32.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes32.LocalPathName = "ESHousekeepingTelemetryData.PerfFilterMask3";
            GES.Communications.DataAttributes dataattributes33 = new GES.Communications.DataAttributes();
            dataattributes33.Name = "PerfFilterMask4";
            dataattributes33.Static = false;
            dataattributes33.DefaultValue = "0";
            dataattributes33.MinValue = "0";
            dataattributes33.MaxValue = "4294967295";
            dataattributes33.DataType = "UInt32";
            dataattributes33.BitLength = 32;
            dataattributes33.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes33.Equation = "";
            dataattributes33.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes33.LocalPathName = "ESHousekeepingTelemetryData.PerfFilterMask4";
            GES.Communications.DataAttributes dataattributes34 = new GES.Communications.DataAttributes();
            dataattributes34.Name = "PerfTriggerMask1";
            dataattributes34.Static = false;
            dataattributes34.DefaultValue = "0";
            dataattributes34.MinValue = "0";
            dataattributes34.MaxValue = "4294967295";
            dataattributes34.DataType = "UInt32";
            dataattributes34.BitLength = 32;
            dataattributes34.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes34.Equation = "";
            dataattributes34.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes34.LocalPathName = "ESHousekeepingTelemetryData.PerfTriggerMask1";
            GES.Communications.DataAttributes dataattributes35 = new GES.Communications.DataAttributes();
            dataattributes35.Name = "PerfTriggerMask2";
            dataattributes35.Static = false;
            dataattributes35.DefaultValue = "0";
            dataattributes35.MinValue = "0";
            dataattributes35.MaxValue = "4294967295";
            dataattributes35.DataType = "UInt32";
            dataattributes35.BitLength = 32;
            dataattributes35.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes35.Equation = "";
            dataattributes35.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes35.LocalPathName = "ESHousekeepingTelemetryData.PerfTriggerMask2";
            GES.Communications.DataAttributes dataattributes36 = new GES.Communications.DataAttributes();
            dataattributes36.Name = "PerfTriggerMask3";
            dataattributes36.Static = false;
            dataattributes36.DefaultValue = "0";
            dataattributes36.MinValue = "0";
            dataattributes36.MaxValue = "4294967295";
            dataattributes36.DataType = "UInt32";
            dataattributes36.BitLength = 32;
            dataattributes36.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes36.Equation = "";
            dataattributes36.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes36.LocalPathName = "ESHousekeepingTelemetryData.PerfTriggerMask3";
            GES.Communications.DataAttributes dataattributes37 = new GES.Communications.DataAttributes();
            dataattributes37.Name = "PerfTriggerMask4";
            dataattributes37.Static = false;
            dataattributes37.DefaultValue = "0";
            dataattributes37.MinValue = "0";
            dataattributes37.MaxValue = "4294967295";
            dataattributes37.DataType = "UInt32";
            dataattributes37.BitLength = 32;
            dataattributes37.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes37.Equation = "";
            dataattributes37.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes37.LocalPathName = "ESHousekeepingTelemetryData.PerfTriggerMask4";
            GES.Communications.DataAttributes dataattributes38 = new GES.Communications.DataAttributes();
            dataattributes38.Name = "PerfDataStart";
            dataattributes38.Static = false;
            dataattributes38.DefaultValue = "0";
            dataattributes38.MinValue = "0";
            dataattributes38.MaxValue = "4294967295";
            dataattributes38.DataType = "UInt32";
            dataattributes38.BitLength = 32;
            dataattributes38.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes38.Equation = "";
            dataattributes38.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes38.LocalPathName = "ESHousekeepingTelemetryData.PerfDataStart";
            GES.Communications.DataAttributes dataattributes39 = new GES.Communications.DataAttributes();
            dataattributes39.Name = "PerfDataEnd";
            dataattributes39.Static = false;
            dataattributes39.DefaultValue = "0";
            dataattributes39.MinValue = "0";
            dataattributes39.MaxValue = "4294967295";
            dataattributes39.DataType = "UInt32";
            dataattributes39.BitLength = 32;
            dataattributes39.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes39.Equation = "";
            dataattributes39.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes39.LocalPathName = "ESHousekeepingTelemetryData.PerfDataEnd";
            GES.Communications.DataAttributes dataattributes40 = new GES.Communications.DataAttributes();
            dataattributes40.Name = "PerfDataCount";
            dataattributes40.Static = false;
            dataattributes40.DefaultValue = "0";
            dataattributes40.MinValue = "0";
            dataattributes40.MaxValue = "4294967295";
            dataattributes40.DataType = "UInt32";
            dataattributes40.BitLength = 32;
            dataattributes40.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes40.Equation = "";
            dataattributes40.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes40.LocalPathName = "ESHousekeepingTelemetryData.PerfDataCount";
            GES.Communications.DataAttributes dataattributes41 = new GES.Communications.DataAttributes();
            dataattributes41.Name = "PerfDataToWrite";
            dataattributes41.Static = false;
            dataattributes41.DefaultValue = "0";
            dataattributes41.MinValue = "0";
            dataattributes41.MaxValue = "4294967295";
            dataattributes41.DataType = "UInt32";
            dataattributes41.BitLength = 32;
            dataattributes41.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes41.Equation = "";
            dataattributes41.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes41.LocalPathName = "ESHousekeepingTelemetryData.PerfDataToWrite";
            GES.Communications.DataAttributes dataattributes42 = new GES.Communications.DataAttributes();
            dataattributes42.Name = "HeapBytesFree";
            dataattributes42.Static = false;
            dataattributes42.DefaultValue = "0";
            dataattributes42.MinValue = "0";
            dataattributes42.MaxValue = "4294967295";
            dataattributes42.DataType = "UInt32";
            dataattributes42.BitLength = 32;
            dataattributes42.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes42.Equation = "";
            dataattributes42.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes42.LocalPathName = "ESHousekeepingTelemetryData.HeapBytesFree";
            GES.Communications.DataAttributes dataattributes43 = new GES.Communications.DataAttributes();
            dataattributes43.Name = "HeapBlockFree";
            dataattributes43.Static = false;
            dataattributes43.DefaultValue = "0";
            dataattributes43.MinValue = "0";
            dataattributes43.MaxValue = "4294967295";
            dataattributes43.DataType = "UInt32";
            dataattributes43.BitLength = 32;
            dataattributes43.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes43.Equation = "";
            dataattributes43.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes43.LocalPathName = "ESHousekeepingTelemetryData.HeapBlockFree";
            GES.Communications.DataAttributes dataattributes44 = new GES.Communications.DataAttributes();
            dataattributes44.Name = "HeapMaxBlockSize";
            dataattributes44.Static = false;
            dataattributes44.DefaultValue = "0";
            dataattributes44.MinValue = "0";
            dataattributes44.MaxValue = "4294967295";
            dataattributes44.DataType = "UInt32";
            dataattributes44.BitLength = 32;
            dataattributes44.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes44.Equation = "";
            dataattributes44.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes44.LocalPathName = "ESHousekeepingTelemetryData.HeapMaxBlockSize";
            CFSTelemetryDefinition.ApplicationDataAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1)),
                    ((GES.Communications.DataAttributes)(dataattributes2)),
                    ((GES.Communications.DataAttributes)(dataattributes3)),
                    ((GES.Communications.DataAttributes)(dataattributes4)),
                    ((GES.Communications.DataAttributes)(dataattributes5)),
                    ((GES.Communications.DataAttributes)(dataattributes6)),
                    ((GES.Communications.DataAttributes)(dataattributes7)),
                    ((GES.Communications.DataAttributes)(dataattributes8)),
                    ((GES.Communications.DataAttributes)(dataattributes9)),
                    ((GES.Communications.DataAttributes)(dataattributes10)),
                    ((GES.Communications.DataAttributes)(dataattributes11)),
                    ((GES.Communications.DataAttributes)(dataattributes12)),
                    ((GES.Communications.DataAttributes)(dataattributes13)),
                    ((GES.Communications.DataAttributes)(dataattributes14)),
                    ((GES.Communications.DataAttributes)(dataattributes15)),
                    ((GES.Communications.DataAttributes)(dataattributes16)),
                    ((GES.Communications.DataAttributes)(dataattributes17)),
                    ((GES.Communications.DataAttributes)(dataattributes18)),
                    ((GES.Communications.DataAttributes)(dataattributes19)),
                    ((GES.Communications.DataAttributes)(dataattributes20)),
                    ((GES.Communications.DataAttributes)(dataattributes21)),
                    ((GES.Communications.DataAttributes)(dataattributes22)),
                    ((GES.Communications.DataAttributes)(dataattributes23)),
                    ((GES.Communications.DataAttributes)(dataattributes24)),
                    ((GES.Communications.DataAttributes)(dataattributes25)),
                    ((GES.Communications.DataAttributes)(dataattributes26)),
                    ((GES.Communications.DataAttributes)(dataattributes27)),
                    ((GES.Communications.DataAttributes)(dataattributes28)),
                    ((GES.Communications.DataAttributes)(dataattributes29)),
                    ((GES.Communications.DataAttributes)(dataattributes30)),
                    ((GES.Communications.DataAttributes)(dataattributes31)),
                    ((GES.Communications.DataAttributes)(dataattributes32)),
                    ((GES.Communications.DataAttributes)(dataattributes33)),
                    ((GES.Communications.DataAttributes)(dataattributes34)),
                    ((GES.Communications.DataAttributes)(dataattributes35)),
                    ((GES.Communications.DataAttributes)(dataattributes36)),
                    ((GES.Communications.DataAttributes)(dataattributes37)),
                    ((GES.Communications.DataAttributes)(dataattributes38)),
                    ((GES.Communications.DataAttributes)(dataattributes39)),
                    ((GES.Communications.DataAttributes)(dataattributes40)),
                    ((GES.Communications.DataAttributes)(dataattributes41)),
                    ((GES.Communications.DataAttributes)(dataattributes42)),
                    ((GES.Communications.DataAttributes)(dataattributes43)),
                    ((GES.Communications.DataAttributes)(dataattributes44))};
            CFSTelemetryDefinition.PrimaryHeader.ApplicationId = (ushort)2048;
            return CFSTelemetryDefinition;
        }
    }
}
