//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Telemetry {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Telemetry.Definitions;
    using CFS.DataStructures;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.Telemetry"})]
    public partial class ExecutiveServicesHousekeepingTelemetery : GES.Communications.CCSDSTelemetry {
        
        private GES.Telemetry.Definitions.CFSTelemetryDefinition _CFSTelemetryDefinition;
        
        private CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData _ESHousekeepingTelemetryData;
        
        public ExecutiveServicesHousekeepingTelemetery() {
            // 
            // Initialize base members
            // 
            this.InitializeBaseMembers();
            // 
            // Construct _CFSTelemetryDefinition
            // 
            this._CFSTelemetryDefinition = ExecutiveServicesHousekeepingTelemetery.CreateCFSTelemetryDefinition();
            // 
            // Construct _ESHousekeepingTelemetryData
            // 
            this._ESHousekeepingTelemetryData = ExecutiveServicesHousekeepingTelemetery.CreateESHousekeepingTelemetryData();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual GES.Telemetry.Definitions.CFSTelemetryDefinition CFSTelemetryDefinition {
            get {
                return this._CFSTelemetryDefinition;
            }
            set {
                this._CFSTelemetryDefinition = value;
                this.OnPropertyChanged("CFSTelemetryDefinition");
            }
        }
        
        public virtual CFS.DataStructures.ExecutiveServicesHousekeepingTelemetryData ESHousekeepingTelemetryData {
            get {
                return this._ESHousekeepingTelemetryData;
            }
            set {
                this._ESHousekeepingTelemetryData = value;
                this.OnPropertyChanged("ESHousekeepingTelemetryData");
            }
        }
        
        private void InitializeBaseMembers() {
            // 
            // Creates a new instance of the GES.Communications.CCSDSTelemetry class CCSDSTelemetry.
            // 
            Name = "ExecutiveServicesHousekeepingTelemetry";
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
            this.Connect("base.PacketDefinition", "CFSTelemetryDefinition");
            this.Connect("CFSTelemetryDefinition.ApplicationData", "ESHousekeepingTelemetryData");
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
