//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    public partial class ExecutiveServicesHousekeepingTelemetryData {
        
        public static uint CreatePerfFilterMask4() {
            // 
            // Creates a new instance of the System.UInt32 class PerfFilterMask4.
            // 
            uint PerfFilterMask4 = default(uint);
            return PerfFilterMask4;
        }
    }
}
