//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class EventServicesApplicationTelemetryData : MTI.Core.Component {
        
        private uint _AppID;
        
        private ushort _AppMessageSentCounter;
        
        private byte _AppEnableStatus;
        
        private byte _Padding;
        
        public EventServicesApplicationTelemetryData() {
            // 
            // Construct _AppID
            // 
            this._AppID = EventServicesApplicationTelemetryData.CreateAppID();
            // 
            // Construct _AppMessageSentCounter
            // 
            this._AppMessageSentCounter = EventServicesApplicationTelemetryData.CreateAppMessageSentCounter();
            // 
            // Construct _AppEnableStatus
            // 
            this._AppEnableStatus = EventServicesApplicationTelemetryData.CreateAppEnableStatus();
            // 
            // Construct _Padding
            // 
            this._Padding = EventServicesApplicationTelemetryData.CreatePadding();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual uint AppID {
            get {
                return this._AppID;
            }
            set {
                this._AppID = value;
                this.OnPropertyChanged("AppID");
            }
        }
        
        public virtual ushort AppMessageSentCounter {
            get {
                return this._AppMessageSentCounter;
            }
            set {
                this._AppMessageSentCounter = value;
                this.OnPropertyChanged("AppMessageSentCounter");
            }
        }
        
        public virtual byte AppEnableStatus {
            get {
                return this._AppEnableStatus;
            }
            set {
                this._AppEnableStatus = value;
                this.OnPropertyChanged("AppEnableStatus");
            }
        }
        
        public virtual byte Padding {
            get {
                return this._Padding;
            }
            set {
                this._Padding = value;
                this.OnPropertyChanged("Padding");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
