//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Tables.Definitions;
    using CFS.Commands;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.Tables"})]
    public partial class ATSTableExample : MTI.Core.Component {
        
        private bool _Start;
        
        private GES.Communications.TimeSequenceSerializer _ATSSerializer;
        
        private CFS.Tables.Definitions.TableDefinitionTemplate _CFSTableDefinition;
        
        private GES.Communications.TableSerializer _TableSerializer;
        
        private CFS.Commands.TelemetryOutputEnableCommand _TelemetryOutputEnableCommand;
        
        public ATSTableExample() {
            // 
            // Construct _Start
            // 
            this._Start = ATSTableExample.CreateStart();
            // 
            // Construct _ATSSerializer
            // 
            this._ATSSerializer = ATSTableExample.CreateATSSerializer();
            // 
            // Construct _CFSTableDefinition
            // 
            this._CFSTableDefinition = ATSTableExample.CreateCFSTableDefinition();
            // 
            // Construct _TableSerializer
            // 
            this._TableSerializer = ATSTableExample.CreateTableSerializer();
            // 
            // Construct _TelemetryOutputEnableCommand
            // 
            this._TelemetryOutputEnableCommand = ATSTableExample.CreateTelemetryOutputEnableCommand();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        [MTI.Core.RequireAttribute(Cut=true)]
        public virtual bool Start {
            get {
                return this._Start;
            }
            set {
                this._Start = value;
                this.OnPropertyChanged("Start");
            }
        }
        
        public virtual GES.Communications.TimeSequenceSerializer ATSSerializer {
            get {
                return this._ATSSerializer;
            }
            set {
                this._ATSSerializer = value;
                this.OnPropertyChanged("ATSSerializer");
            }
        }
        
        public virtual CFS.Tables.Definitions.TableDefinitionTemplate CFSTableDefinition {
            get {
                return this._CFSTableDefinition;
            }
            set {
                this._CFSTableDefinition = value;
                this.OnPropertyChanged("CFSTableDefinition");
            }
        }
        
        public virtual GES.Communications.TableSerializer TableSerializer {
            get {
                return this._TableSerializer;
            }
            set {
                this._TableSerializer = value;
                this.OnPropertyChanged("TableSerializer");
            }
        }
        
        [MTI.Core.ProvideAttribute(Alias="TableSerializer.Ready")]
        public virtual bool Ready {
            get {
                return this._TableSerializer.Ready;
            }
            set {
                this._TableSerializer.Ready = value;
                this.OnPropertyChanged("TableSerializer.Ready");
            }
        }
        
        public virtual CFS.Commands.TelemetryOutputEnableCommand TelemetryOutputEnableCommand {
            get {
                return this._TelemetryOutputEnableCommand;
            }
            set {
                this._TelemetryOutputEnableCommand = value;
                this.OnPropertyChanged("TelemetryOutputEnableCommand");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
            this.Connect("ATSSerializer.Start", "Start");
            this.Connect("ATSSerializer.Commands", "TelemetryOutputEnableCommand");
            this.Connect("CFSTableDefinition.Content", "ATSSerializer.SerializedBytes");
            this.Connect("TableSerializer.Start", "ATSSerializer.Ready");
            this.Connect("TableSerializer.TableDefinition", "CFSTableDefinition");
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
