//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Tables.Definitions;
    using CFS.Commands;
    
    
    public partial class ATSTableExample {
        
        public static bool CreateStart() {
            // 
            // Creates a new instance of the System.Boolean class Start.
            // 
            bool Start = default(bool);
            return Start;
        }
    }
}
