//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Tables.Definitions;
    using CFS.Commands;
    
    
    public partial class ATSTableExample {
        
        public static CFS.Tables.Definitions.TableDefinitionTemplate CreateCFSTableDefinition() {
            // 
            // Creates a new instance of the CFS.Tables.Definitions.TableDefinitionTemplate class CFSTableDefinition.
            // 
            CFS.Tables.Definitions.TableDefinitionTemplate CFSTableDefinition = new CFS.Tables.Definitions.TableDefinitionTemplate();
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "SerializedBytes";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "";
            dataattributes1.MinValue = "0";
            dataattributes1.MaxValue = "255";
            dataattributes1.DataType = "Byte[]";
            dataattributes1.BitLength = 240;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "ATSSerializer.SerializedBytes";
            CFSTableDefinition.ContentAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1))};
            CFSTableDefinition.CFETableHeader.TableName = "SC.ATS_TBL2";
            CFSTableDefinition.CFETableHeader.NumBytes = 30u;
            CFSTableDefinition.CFETableHeader.Offset = 0u;
            return CFSTableDefinition;
        }
    }
}
