//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class TableValidateCommandData : MTI.Core.Component {
        
        private ushort _ActiveTableFlag;
        
        private string _TableName;
        
        public TableValidateCommandData() {
            // 
            // Construct _ActiveTableFlag
            // 
            this._ActiveTableFlag = TableValidateCommandData.CreateActiveTableFlag();
            // 
            // Construct _TableName
            // 
            this._TableName = TableValidateCommandData.CreateTableName();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual ushort ActiveTableFlag {
            get {
                return this._ActiveTableFlag;
            }
            set {
                this._ActiveTableFlag = value;
                this.OnPropertyChanged("ActiveTableFlag");
            }
        }
        
        public virtual string TableName {
            get {
                return this._TableName;
            }
            set {
                this._TableName = value;
                this.OnPropertyChanged("TableName");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
