//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class TableDefinitionTemplate {
        
        public static CFS.DataStructures.CFEFileHeader CreateCFEFileHeader() {
            // 
            // Creates a new instance of the CFS.DataStructures.CFEFileHeader class CFEFileHeader.
            // 
            CFS.DataStructures.CFEFileHeader CFEFileHeader = new CFS.DataStructures.CFEFileHeader();
            CFEFileHeader.SubType = 8u;
            CFEFileHeader.Length = 64u;
            CFEFileHeader.ContentType = 1665549617u;
            return CFEFileHeader;
        }
    }
}
