//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class TableDefinitionTemplate {
        
        public static GES.Communications.TableDefinition CreateTableDefinition() {
            // 
            // Creates a new instance of the GES.Communications.TableDefinition class TableDefinition.
            // 
            GES.Communications.TableDefinition TableDefinition = new GES.Communications.TableDefinition();
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "ContentType";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "1665549617";
            dataattributes1.MinValue = "0";
            dataattributes1.MaxValue = "4294967295";
            dataattributes1.DataType = "UInt32";
            dataattributes1.BitLength = 32;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "CFEFileHeader.ContentType";
            GES.Communications.DataAttributes dataattributes2 = new GES.Communications.DataAttributes();
            dataattributes2.Name = "SubType";
            dataattributes2.Static = false;
            dataattributes2.DefaultValue = "0";
            dataattributes2.MinValue = "0";
            dataattributes2.MaxValue = "4294967295";
            dataattributes2.DataType = "UInt32";
            dataattributes2.BitLength = 32;
            dataattributes2.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes2.Equation = "";
            dataattributes2.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes2.LocalPathName = "CFEFileHeader.SubType";
            GES.Communications.DataAttributes dataattributes3 = new GES.Communications.DataAttributes();
            dataattributes3.Name = "Length";
            dataattributes3.Static = false;
            dataattributes3.DefaultValue = "0";
            dataattributes3.MinValue = "0";
            dataattributes3.MaxValue = "4294967295";
            dataattributes3.DataType = "UInt32";
            dataattributes3.BitLength = 32;
            dataattributes3.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes3.Equation = "";
            dataattributes3.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes3.LocalPathName = "CFEFileHeader.Length";
            GES.Communications.DataAttributes dataattributes4 = new GES.Communications.DataAttributes();
            dataattributes4.Name = "SpacecraftID";
            dataattributes4.Static = false;
            dataattributes4.DefaultValue = "0";
            dataattributes4.MinValue = "0";
            dataattributes4.MaxValue = "4294967295";
            dataattributes4.DataType = "UInt32";
            dataattributes4.BitLength = 32;
            dataattributes4.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes4.Equation = "";
            dataattributes4.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes4.LocalPathName = "CFEFileHeader.SpacecraftID";
            GES.Communications.DataAttributes dataattributes5 = new GES.Communications.DataAttributes();
            dataattributes5.Name = "ProcessorID";
            dataattributes5.Static = false;
            dataattributes5.DefaultValue = "0";
            dataattributes5.MinValue = "0";
            dataattributes5.MaxValue = "4294967295";
            dataattributes5.DataType = "UInt32";
            dataattributes5.BitLength = 32;
            dataattributes5.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes5.Equation = "";
            dataattributes5.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes5.LocalPathName = "CFEFileHeader.ProcessorID";
            GES.Communications.DataAttributes dataattributes6 = new GES.Communications.DataAttributes();
            dataattributes6.Name = "ApplicationID";
            dataattributes6.Static = false;
            dataattributes6.DefaultValue = "0";
            dataattributes6.MinValue = "0";
            dataattributes6.MaxValue = "4294967295";
            dataattributes6.DataType = "UInt32";
            dataattributes6.BitLength = 32;
            dataattributes6.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes6.Equation = "";
            dataattributes6.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes6.LocalPathName = "CFEFileHeader.ApplicationID";
            GES.Communications.DataAttributes dataattributes7 = new GES.Communications.DataAttributes();
            dataattributes7.Name = "TimeSeconds";
            dataattributes7.Static = false;
            dataattributes7.DefaultValue = "0";
            dataattributes7.MinValue = "2147483647";
            dataattributes7.MaxValue = "2147483647";
            dataattributes7.DataType = "Int32";
            dataattributes7.BitLength = 32;
            dataattributes7.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes7.Equation = "";
            dataattributes7.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes7.LocalPathName = "CFEFileHeader.TimeSeconds";
            GES.Communications.DataAttributes dataattributes8 = new GES.Communications.DataAttributes();
            dataattributes8.Name = "TimeSubseconds";
            dataattributes8.Static = false;
            dataattributes8.DefaultValue = "0";
            dataattributes8.MinValue = "0";
            dataattributes8.MaxValue = "4294967295";
            dataattributes8.DataType = "UInt32";
            dataattributes8.BitLength = 32;
            dataattributes8.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes8.Equation = "";
            dataattributes8.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes8.LocalPathName = "CFEFileHeader.TimeSubseconds";
            GES.Communications.DataAttributes dataattributes9 = new GES.Communications.DataAttributes();
            dataattributes9.Name = "Description";
            dataattributes9.Static = false;
            dataattributes9.DefaultValue = "";
            dataattributes9.MinValue = "";
            dataattributes9.MaxValue = "";
            dataattributes9.DataType = "String";
            dataattributes9.BitLength = 256;
            dataattributes9.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes9.Equation = "";
            dataattributes9.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes9.LocalPathName = "CFEFileHeader.Description";
            TableDefinition.FileHeaderAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1)),
                    ((GES.Communications.DataAttributes)(dataattributes2)),
                    ((GES.Communications.DataAttributes)(dataattributes3)),
                    ((GES.Communications.DataAttributes)(dataattributes4)),
                    ((GES.Communications.DataAttributes)(dataattributes5)),
                    ((GES.Communications.DataAttributes)(dataattributes6)),
                    ((GES.Communications.DataAttributes)(dataattributes7)),
                    ((GES.Communications.DataAttributes)(dataattributes8)),
                    ((GES.Communications.DataAttributes)(dataattributes9))};
            GES.Communications.DataAttributes dataattributes10 = new GES.Communications.DataAttributes();
            dataattributes10.Name = "Reserved";
            dataattributes10.Static = false;
            dataattributes10.DefaultValue = "0";
            dataattributes10.MinValue = "0";
            dataattributes10.MaxValue = "4294967295";
            dataattributes10.DataType = "UInt32";
            dataattributes10.BitLength = 32;
            dataattributes10.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes10.Equation = "";
            dataattributes10.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes10.LocalPathName = "CFETableHeader.Reserved";
            GES.Communications.DataAttributes dataattributes11 = new GES.Communications.DataAttributes();
            dataattributes11.Name = "Offset";
            dataattributes11.Static = false;
            dataattributes11.DefaultValue = "0";
            dataattributes11.MinValue = "0";
            dataattributes11.MaxValue = "4294967295";
            dataattributes11.DataType = "UInt32";
            dataattributes11.BitLength = 32;
            dataattributes11.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes11.Equation = "";
            dataattributes11.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes11.LocalPathName = "CFETableHeader.Offset";
            GES.Communications.DataAttributes dataattributes12 = new GES.Communications.DataAttributes();
            dataattributes12.Name = "NumBytes";
            dataattributes12.Static = false;
            dataattributes12.DefaultValue = "0";
            dataattributes12.MinValue = "0";
            dataattributes12.MaxValue = "4294967295";
            dataattributes12.DataType = "UInt32";
            dataattributes12.BitLength = 32;
            dataattributes12.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes12.Equation = "";
            dataattributes12.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes12.LocalPathName = "CFETableHeader.NumBytes";
            GES.Communications.DataAttributes dataattributes13 = new GES.Communications.DataAttributes();
            dataattributes13.Name = "TableName";
            dataattributes13.Static = false;
            dataattributes13.DefaultValue = "";
            dataattributes13.MinValue = "";
            dataattributes13.MaxValue = "";
            dataattributes13.DataType = "String";
            dataattributes13.BitLength = 320;
            dataattributes13.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes13.Equation = "";
            dataattributes13.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes13.LocalPathName = "CFETableHeader.TableName";
            TableDefinition.TableHeaderAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes10)),
                    ((GES.Communications.DataAttributes)(dataattributes11)),
                    ((GES.Communications.DataAttributes)(dataattributes12)),
                    ((GES.Communications.DataAttributes)(dataattributes13))};
            TableDefinition.ContentAttributes = new GES.Communications.DataAttributes[0];
            return TableDefinition;
        }
    }
}
