//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class TableDefinitionTemplate {
        
        public static CFS.DataStructures.CFETableHeader CreateCFETableHeader() {
            // 
            // Creates a new instance of the CFS.DataStructures.CFETableHeader class CFETableHeader.
            // 
            CFS.DataStructures.CFETableHeader CFETableHeader = new CFS.DataStructures.CFETableHeader();
            return CFETableHeader;
        }
    }
}
