//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tasks {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Commands;
    using CFS.Telemetry;
    
    
    public partial class CommandUplink {
        
        public static CFS.Commands.TableValidateCommand CreateTableValidateCommand() {
            // 
            // Creates a new instance of the CFS.Commands.TableValidateCommand class TableValidateCommand.
            // 
            CFS.Commands.TableValidateCommand TableValidateCommand = new CFS.Commands.TableValidateCommand();
            TableValidateCommand.TableValidateCommandData.ActiveTableFlag = 0;
            TableValidateCommand.TableValidateCommandData.TableName = "SC.ATS_TBL2";
            TableValidateCommand.TableValidateCommandData.ActiveTableFlag = 0;
            TableValidateCommand.TableValidateCommandData.TableName = "SC.ATS_TBL2";
            return TableValidateCommand;
        }
    }
}
