//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tasks {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Commands;
    using CFS.Telemetry;
    
    
    public partial class CommandUplink {
        
        public static GES.Communications.TelemetryTask CreateTelemetryTask() {
            // 
            // Creates a new instance of the GES.Communications.TelemetryTask class TelemetryTask.
            // 
            GES.Communications.TelemetryTask TelemetryTask = new GES.Communications.TelemetryTask();
            TelemetryTask.TaskId = 0;
            return TelemetryTask;
        }
    }
}
