//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tasks {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.Commands;
    using CFS.Telemetry;
    
    
    public partial class CommandUplink {
        
        public static GES.Communications.SocketTransceiver CreateReceiver() {
            // 
            // Creates a new instance of the GES.Communications.SocketTransceiver class Receiver.
            // 
            GES.Communications.SocketTransceiver Receiver = new GES.Communications.SocketTransceiver();
            Receiver.AddressOrHostName = "192.168.001.200";
            Receiver.Port = 1235;
            Receiver.Protocol = System.Net.Sockets.ProtocolType.Udp;
            Receiver.Verbose = true;
            return Receiver;
        }
    }
}
