//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Telemetry.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class CFSTelemetryDefinition {
        
        public static GES.Communications.CCSDSPacketDefinition CreateCCSDSPacketDefinition() {
            // 
            // Creates a new instance of the GES.Communications.CCSDSPacketDefinition class CCSDSPacketDefinition.
            // 
            GES.Communications.CCSDSPacketDefinition CCSDSPacketDefinition = new GES.Communications.CCSDSPacketDefinition();
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "Seconds";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "0";
            dataattributes1.MinValue = "0";
            dataattributes1.MaxValue = "4294967295";
            dataattributes1.DataType = "UInt32";
            dataattributes1.BitLength = 32;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "TelemetrySecondaryHeader.Seconds";
            GES.Communications.DataAttributes dataattributes2 = new GES.Communications.DataAttributes();
            dataattributes2.Name = "Subseconds";
            dataattributes2.Static = false;
            dataattributes2.DefaultValue = "0";
            dataattributes2.MinValue = "0";
            dataattributes2.MaxValue = "65535";
            dataattributes2.DataType = "UInt16";
            dataattributes2.BitLength = 16;
            dataattributes2.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes2.Equation = "";
            dataattributes2.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes2.LocalPathName = "TelemetrySecondaryHeader.Subseconds";
            CCSDSPacketDefinition.SecondaryHeaderAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1)),
                    ((GES.Communications.DataAttributes)(dataattributes2))};
            return CCSDSPacketDefinition;
        }
    }
}
