//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Telemetry.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    public partial class CFSTelemetryDefinition {
        
        public static CFS.DataStructures.TelemetrySecondaryHeader CreateTelemetrySecondaryHeader() {
            // 
            // Creates a new instance of the CFS.DataStructures.TelemetrySecondaryHeader class TelemetrySecondaryHeader.
            // 
            CFS.DataStructures.TelemetrySecondaryHeader TelemetrySecondaryHeader = new CFS.DataStructures.TelemetrySecondaryHeader();
            return TelemetrySecondaryHeader;
        }
    }
}
