//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    
    
    public partial class StartATSCommand {
        
        public static CFS.Commands.CFSCommand CreateCFSCommand() {
            // 
            // Creates a new instance of the CFS.Commands.CFSCommand class CFSCommand.
            // 
            CFS.Commands.CFSCommand CFSCommand = new CFS.Commands.CFSCommand();
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.ApplicationId = 6313;
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "AtsId";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "0";
            dataattributes1.MinValue = "0";
            dataattributes1.MaxValue = "65535";
            dataattributes1.DataType = "UInt16";
            dataattributes1.BitLength = 16;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.LittleEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "AtsId";
            CFSCommand.CCSDSPacketDefinition.ApplicationDataAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1))};
            CFSCommand.CommandSecondaryHeader.FunctionCode = 2;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.Version = 0;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.Type = 1;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.SecondaryFlag = 1;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.ApplicationId = 6313;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.Grouping = 2;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.SequenceCount = 0;
            CFSCommand.CCSDSPacketDefinition.PrimaryHeader.PacketDataLength = 3;
            return CFSCommand;
        }
    }
}
