//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    
    
    public partial class StartATSCommand {
        
        public static ushort CreateAtsId() {
            // 
            // Creates a new instance of the System.UInt16 class AtsId.
            // 
            ushort AtsId = default(ushort);
            return AtsId;
        }
    }
}
