//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    
    
    public partial class CommandSequence3 {
        
        public static CFS.Commands.TelemetryOutputEnableCommand CreateTelemetryOutputEnableCommand1() {
            // 
            // Creates a new instance of the CFS.Commands.TelemetryOutputEnableCommand class TelemetryOutputEnableCommand1.
            // 
            CFS.Commands.TelemetryOutputEnableCommand TelemetryOutputEnableCommand1 = new CFS.Commands.TelemetryOutputEnableCommand();
            return TelemetryOutputEnableCommand1;
        }
    }
}
