//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Telemetry {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Telemetry.Definitions;
    using CFS.DataStructures;
    
    
    public partial class EventServicesHousekeepingTelemetery {
        
        public static CFS.DataStructures.EventServicesHousekeepingTelemetreyData CreateEVSHousekeepingTelemetreyData() {
            // 
            // Creates a new instance of the CFS.DataStructures.EventServicesHousekeepingTelemetreyData class EVSHousekeepingTelemetreyData.
            // 
            CFS.DataStructures.EventServicesHousekeepingTelemetreyData EVSHousekeepingTelemetreyData = new CFS.DataStructures.EventServicesHousekeepingTelemetreyData();
            return EVSHousekeepingTelemetreyData;
        }
    }
}
