//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Commands.Definitions;
    using CFS.DataStructures;
    
    
    public partial class TableValidateCommand {
        
        public static CFS.DataStructures.TableValidateCommandData CreateTableValidateCommandData() {
            // 
            // Creates a new instance of the CFS.DataStructures.TableValidateCommandData class TableValidateCommandData.
            // 
            CFS.DataStructures.TableValidateCommandData TableValidateCommandData = new CFS.DataStructures.TableValidateCommandData();
            TableValidateCommandData.ActiveTableFlag = 1;
            TableValidateCommandData.TableName = "";
            return TableValidateCommandData;
        }
    }
}
