//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Commands.Definitions {
    using System;
    using MTI.Core;
    using GES.Communications;
    using CFS.DataStructures;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "GES.Commands.Definitions"})]
    public partial class CFSCommandDefinition : GES.Communications.CCSDSPacketDefinition {
        
        private CFS.DataStructures.CommandSecondaryHeader _CommandSecondaryHeader;
        
        private GES.Communications.XORChecksum _XORChecksum;
        
        public CFSCommandDefinition() {
            // 
            // Initialize base members
            // 
            this.InitializeBaseMembers();
            // 
            // Construct _CommandSecondaryHeader
            // 
            this._CommandSecondaryHeader = CFSCommandDefinition.CreateCommandSecondaryHeader();
            // 
            // Construct _XORChecksum
            // 
            this._XORChecksum = CFSCommandDefinition.CreateXORChecksum();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public new virtual object SecondaryHeader {
            get {
                return base.SecondaryHeader;
            }
            set {
                base.SecondaryHeader = value;
                this.OnPropertyChanged("CCSDSPacketDefinition.SecondaryHeader");
            }
        }
        
        public new virtual GES.Communications.Checksum Checksum {
            get {
                return base.Checksum;
            }
            set {
                base.Checksum = value;
                this.OnPropertyChanged("CCSDSPacketDefinition.Checksum");
            }
        }
        
        public virtual CFS.DataStructures.CommandSecondaryHeader CommandSecondaryHeader {
            get {
                return this._CommandSecondaryHeader;
            }
            set {
                this._CommandSecondaryHeader = value;
                this.OnPropertyChanged("CommandSecondaryHeader");
            }
        }
        
        public virtual GES.Communications.XORChecksum XORChecksum {
            get {
                return this._XORChecksum;
            }
            set {
                this._XORChecksum = value;
                this.OnPropertyChanged("XORChecksum");
            }
        }
        
        private void InitializeBaseMembers() {
            // 
            // Creates a new instance of the GES.Communications.CCSDSPacketDefinition class CCSDSPacketDefinition.
            // 
            GES.Communications.DataAttributes dataattributes3 = new GES.Communications.DataAttributes();
            dataattributes3.Name = "Checksum";
            dataattributes3.Static = false;
            dataattributes3.DefaultValue = "0";
            dataattributes3.MinValue = "0";
            dataattributes3.MaxValue = "255";
            dataattributes3.DataType = "Byte";
            dataattributes3.BitLength = 8;
            dataattributes3.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes3.Equation = "";
            dataattributes3.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes3.LocalPathName = "CommandSecondaryHeader.Checksum";
            GES.Communications.DataAttributes dataattributes4 = new GES.Communications.DataAttributes();
            dataattributes4.Name = "FunctionCode";
            dataattributes4.Static = false;
            dataattributes4.DefaultValue = "0";
            dataattributes4.MinValue = "0";
            dataattributes4.MaxValue = "255";
            dataattributes4.DataType = "Byte";
            dataattributes4.BitLength = 8;
            dataattributes4.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes4.Equation = "";
            dataattributes4.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes4.LocalPathName = "CommandSecondaryHeader.FunctionCode";
            base.SecondaryHeaderAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes3)),
                    ((GES.Communications.DataAttributes)(dataattributes4))};
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
            this.Connect("base.SecondaryHeader", "CommandSecondaryHeader");
            this.Connect("base.Checksum", "XORChecksum");
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
