//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    public partial class NETIFInitSocketCommandData {
        
        public static short CreateServerPort() {
            // 
            // Creates a new instance of the System.Int16 class ServerPort.
            // 
            short ServerPort = default(short);
            return ServerPort;
        }
    }
}
