//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class NETIFInitSocketCommandData : MTI.Core.Component {
        
        private short _ServerPort;
        
        private string _IPAddress;
        
        public NETIFInitSocketCommandData() {
            // 
            // Construct _ServerPort
            // 
            this._ServerPort = NETIFInitSocketCommandData.CreateServerPort();
            // 
            // Construct _IPAddress
            // 
            this._IPAddress = NETIFInitSocketCommandData.CreateIPAddress();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual short ServerPort {
            get {
                return this._ServerPort;
            }
            set {
                this._ServerPort = value;
                this.OnPropertyChanged("ServerPort");
            }
        }
        
        public virtual string IPAddress {
            get {
                return this._IPAddress;
            }
            set {
                this._IPAddress = value;
                this.OnPropertyChanged("IPAddress");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
