//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using CFS.Tables.Definitions;
    using GES.Communications;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.Tables"})]
    public partial class CFSTableTemplate : MTI.Core.Component {
        
        private CFS.Tables.Definitions.TableDefinitionTemplate _CFSTableDefinition;
        
        private GES.Communications.TableSerializer _TableSerializer;
        
        public CFSTableTemplate() {
            // 
            // Construct _CFSTableDefinition
            // 
            this._CFSTableDefinition = CFSTableTemplate.CreateCFSTableDefinition();
            // 
            // Construct _TableSerializer
            // 
            this._TableSerializer = CFSTableTemplate.CreateTableSerializer();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual CFS.Tables.Definitions.TableDefinitionTemplate CFSTableDefinition {
            get {
                return this._CFSTableDefinition;
            }
            set {
                this._CFSTableDefinition = value;
                this.OnPropertyChanged("CFSTableDefinition");
            }
        }
        
        [MTI.Core.RequireAttribute(Cut=true, Alias="CFSTableDefinition.Content")]
        public virtual object Content {
            get {
                return this._CFSTableDefinition.Content;
            }
            set {
                this._CFSTableDefinition.Content = value;
                this.OnPropertyChanged("CFSTableDefinition.Content");
            }
        }
        
        public virtual GES.Communications.TableSerializer TableSerializer {
            get {
                return this._TableSerializer;
            }
            set {
                this._TableSerializer = value;
                this.OnPropertyChanged("TableSerializer");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
            this.Connect("TableSerializer.TableDefinition", "CFSTableDefinition");
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
