//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using CFS.Tables.Definitions;
    using GES.Communications;
    
    
    public partial class CFSTableTemplate {
        
        public static CFS.Tables.Definitions.TableDefinitionTemplate CreateCFSTableDefinition() {
            // 
            // Creates a new instance of the CFS.Tables.Definitions.TableDefinitionTemplate class CFSTableDefinition.
            // 
            CFS.Tables.Definitions.TableDefinitionTemplate CFSTableDefinition = new CFS.Tables.Definitions.TableDefinitionTemplate();
            return CFSTableDefinition;
        }
    }
}
