//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Tables {
    using System;
    using MTI.Core;
    using CFS.Tables.Definitions;
    using GES.Communications;
    
    
    public partial class CFSTableTemplate {
        
        public static GES.Communications.TableSerializer CreateTableSerializer() {
            // 
            // Creates a new instance of the GES.Communications.TableSerializer class TableSerializer.
            // 
            GES.Communications.TableSerializer TableSerializer = new GES.Communications.TableSerializer();
            TableSerializer.Filename = "C:\\Projects\\SystemManager64\\UserLibrary\\CFS.Tables\\CFSTableTemplate\\table.tbl";
            return TableSerializer;
        }
    }
}
