//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.Commands {
    using System;
    using MTI.Core;
    using GES.Communications;
    using GES.Commands.Definitions;
    using CFS.DataStructures;
    
    
    public partial class NETIFInitSocketCommand {
        
        public static GES.Commands.Definitions.CFSCommandDefinition CreateCFSCommandDefinition() {
            // 
            // Creates a new instance of the GES.Commands.Definitions.CFSCommandDefinition class CFSCommandDefinition.
            // 
            GES.Commands.Definitions.CFSCommandDefinition CFSCommandDefinition = new GES.Commands.Definitions.CFSCommandDefinition();
            CFSCommandDefinition.CommandSecondaryHeader.FunctionCode = 4;
            GES.Communications.DataAttributes dataattributes1 = new GES.Communications.DataAttributes();
            dataattributes1.Name = "ServerPort";
            dataattributes1.Static = false;
            dataattributes1.DefaultValue = "0";
            dataattributes1.MinValue = "-32768";
            dataattributes1.MaxValue = "32767";
            dataattributes1.DataType = "Int16";
            dataattributes1.BitLength = 16;
            dataattributes1.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes1.Equation = "";
            dataattributes1.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes1.LocalPathName = "NETIFInitSocketCommandData.ServerPort";
            GES.Communications.DataAttributes dataattributes2 = new GES.Communications.DataAttributes();
            dataattributes2.Name = "IPAddress";
            dataattributes2.Static = false;
            dataattributes2.DefaultValue = "";
            dataattributes2.MinValue = "";
            dataattributes2.MaxValue = "";
            dataattributes2.DataType = "String";
            dataattributes2.BitLength = 128;
            dataattributes2.Endian = GES.Communications.DataAttributes.EndianType.BigEndian;
            dataattributes2.Equation = "";
            dataattributes2.EnumeratedValues = new GES.Communications.DataAttributes.Enumeration[0];
            dataattributes2.LocalPathName = "NETIFInitSocketCommandData.IPAddress";
            CFSCommandDefinition.ApplicationDataAttributes = new GES.Communications.DataAttributes[] {
                    ((GES.Communications.DataAttributes)(dataattributes1)),
                    ((GES.Communications.DataAttributes)(dataattributes2))};
            CFSCommandDefinition.PrimaryHeader.Version = 0;
            CFSCommandDefinition.PrimaryHeader.Type = 1;
            CFSCommandDefinition.PrimaryHeader.SecondaryFlag = 1;
            CFSCommandDefinition.PrimaryHeader.ApplicationId = 6400;
            CFSCommandDefinition.PrimaryHeader.Grouping = 3;
            CFSCommandDefinition.PrimaryHeader.SequenceCount = 0;
            CFSCommandDefinition.PrimaryHeader.PacketDataLength = 19;
            CFSCommandDefinition.XORChecksum.StopIndex = 26;
            return CFSCommandDefinition;
        }
    }
}
