//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS.DataStructures {
    using System;
    using MTI.Core;
    
    
    [MTI.Core.ProvideAttribute(Categories=new string[] {
            "CFS.DataStructures"})]
    public partial class TelemetrySecondaryHeader : MTI.Core.Component {
        
        private uint _Seconds;
        
        private ushort _Subseconds;
        
        public TelemetrySecondaryHeader() {
            // 
            // Construct _Seconds
            // 
            this._Seconds = TelemetrySecondaryHeader.CreateSeconds();
            // 
            // Construct _Subseconds
            // 
            this._Subseconds = TelemetrySecondaryHeader.CreateSubseconds();
            // 
            // Connect Graph
            // 
            this.Connect();
        }
        
        public virtual uint Seconds {
            get {
                return this._Seconds;
            }
            set {
                this._Seconds = value;
                this.OnPropertyChanged("Seconds");
            }
        }
        
        public virtual ushort Subseconds {
            get {
                return this._Subseconds;
            }
            set {
                this._Subseconds = value;
                this.OnPropertyChanged("Subseconds");
            }
        }
        
        public virtual void Connect() {
            // 
            // Connects subcomponents into graph 
            // 
        }
        
        public override bool OnInitialize() {
            // 
            // Initialize subcomponents
            // 
            return base.OnInitialize();
        }
    }
}
